### ISSUE TITLE
Set up error

### ISSUE THREAD

**Issue by anilkanthi** [higlass/clodius#126]
Hi,

I am trying to set up the tool for HiGlass analysis, but it gives an error when the command is run:

module load python/cpu/2.7.15
clodius 

Traceback (most recent call last):
  File "/gpfs/share/apps/python/cpu/2.7.15-ES/bin/clodius", line 5, in <module>
    from clodius.cli.aggregate import cli
  File "/gpfs/share/apps/python/cpu/2.7.15-ES/lib/python2.7/site-packages/clodius/cli/__init__.py", line 18, in <module>
    from . import (  # noqa: F401
  File "/gpfs/share/apps/python/cpu/2.7.15-ES/lib/python2.7/site-packages/clodius/cli/aggregate.py", line 539
    f"Unable to find {line_parts[0]} in the list of chromosome sizes. "
                                                                      ^
SyntaxError: invalid syntax

**Comment by nvictus** [comment]
Looks like you are using Python 2.7. Clodius requires Python 3.

**Comment by anilkanthi** [comment]
Great will try that out. Thanks!
