### ISSUE TITLE
Error in aggregate: slugid no longer needs decoding

### ISSUE THREAD

**Issue by liz-is** [higlass/clodius#48]
Hi there,
I'm getting the following error trying to aggregate a bedpe file:

```
output_file: consensus_loops_all_peaks.hitile
plain
Traceback (most recent call last):
  File "/home/lingsim/.linuxbrew/bin/clodius", line 10, in <module>
    sys.exit(cli())
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 1548, in bedpe
    chr2_col=chr2_col-1, from2_col=from2_col-1, to2_col=to2_col-1
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 261, in _bedpe
    entries = [line_to_dict(first_line)]
  File "/home/lingsim/.linuxbrew/opt/python/lib/python3.7/site-packages/clodius/cli/aggregate.py", line 216, in line_to_dict
    d['uid'] = slugid.nice().decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

This appears to be because [slugid recently changed to now return a string](https://github.com/taskcluster/slugid.py/commit/162b30c6670d7878a5aabb5374857e7faff5ffdb), so it no longer needs decoding. 

(I'm happy to make a pull request with a fix if it's as simple as removing the decode, but I'm not familiar with what's necessary for compatibility with both Python2 and Python3, if that's a concern here.)

**Comment by pkerpedjiev** [comment]
Removing decode is all that's necessary. This is just because the `slugid` package had a major update that removed the need for `decode`.

A PR would be very welcome :-)
