### ISSUE TITLE
bigwig_test.py fails with "numpy.ufunc size changed"

### ISSUE THREAD

**Issue by mccalluc** [higlass/clodius#79]
Running tests I get this error. I'm on the branch for PR #71. I've installed dependencies with `pip install -r requirements.txt`.

<details>

```
ERROR: Failure: ValueError (numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chuck/anaconda3/envs/clodius/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/chuck/anaconda3/envs/clodius/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/chuck/anaconda3/envs/clodius/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/chuck/anaconda3/envs/clodius/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/chuck/anaconda3/envs/clodius/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/chuck/anaconda3/envs/clodius/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/chuck/github/higlass/clodius/test/tiles/bigwig_test.py", line 1, in <module>
    import clodius.tiles.bigwig as hgbi
  File "/Users/chuck/github/higlass/clodius/clodius/tiles/bigwig.py", line 1, in <module>
    import bbi
  File "/Users/chuck/anaconda3/envs/clodius/lib/python3.6/site-packages/pybbi-0.2.0-py3.6-macosx-10.7-x86_64.egg/bbi/__init__.py", line 3, in <module>
    from .cbbi import (
  File ".eggs/Cython-0.29.6-py3.6-macosx-10.7-x86_64.egg/Cython/Includes/numpy/__init__.pxd", line 918, in init bbi.cbbi
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

</details>

**Comment by nvictus** [comment]
Seems like a conflict between the numpy C headers `pybbi` was built against and the actual numpy version being imported. Your env might have two numpys (one from conda and one from pip).
